function createPieces ()
{
  team = {
  "white":
[
  {
    "piece": pawnPiece,
    "row": 1,
    "col": 0,
    "status": inUse
  },
  {
    "piece": pawnPiece,
    "row": 1,
    "col": 1,
    "status": inUse
  },
  {
    "piece": pawnPiece,
    "row": 1,
    "col": 2,
    "status": inUse
  },
  {
    "piece": pawnPiece,
    "row": 1,
    "col": 3,
    "status": inUse
  },
  {
    "piece": pawnPiece,
    "row": 1,
    "col": 4,
    "status": inUse
  },
  {
    "piece": pawnPiece,
    "row": 1,
    "col": 5,
    "status": inUse
  },
  {
    "piece": pawnPiece,
    "row": 1,
    "col": 6,
    "status": inUse
  },
  {
    "piece": pawnPiece,
    "row": 1,
    "col": 7,
    "status": inUse
  },

  {
    "piece": rookPiece,
    "row": 0,
    "col": 0,
    "status": inUse
  },
  {
    "piece": rookPiece,
    "row": 0,
    "col": 7,
    "status": inUse
  },
  {
    "piece": knightPiece,
    "row": 0,
    "col": 1,
    "status": inUse
  },
  {
    "piece": knightPiece,
    "row": 0,
    "col": 6,
    "status": inUse
  },
  {
    "piece": bishopPiece,
    "row": 0,
    "col": 2,
    "status": inUse
  },
  {
    "piece": bishopPiece,
    "row": 0,
    "col": 5,
    "status": inUse
  },
  {
    "piece": queenPiece,
    "row": 0,
    "col": 4,
    "status": inUse
  },
  {
    "piece": kingPiece,
    "row": 0,
    "col": 3,
    "status": inUse
  }
],
"black":
[
  {
    "piece": pawnPiece,
    "row": 6,
    "col": 0,
    "status": inUse
  },
  {
    "piece": pawnPiece,
    "row": 6,
    "col": 1,
    "status": inUse
  },
  {
    "piece": pawnPiece,
    "row": 6,
    "col": 2,
    "status": inUse
  },
  {
    "piece": pawnPiece,
    "row": 6,
    "col": 3,
    "status": inUse
  },
  {
    "piece": pawnPiece,
    "row": 6,
    "col": 4,
    "status": inUse
  },
  {
    "piece": pawnPiece,
    "row": 6,
    "col": 5,
    "status": inUse
  },
  {
    "piece": pawnPiece,
    "row": 6,
    "col": 6,
    "status": inUse
  },
  {
    "piece": pawnPiece,
    "row": 6,
    "col": 7,
    "status": inUse
  },

  {
    "piece": rookPiece,
    "row": 7,
    "col": 0,
    "status": inUse
  },
  {
    "piece": rookPiece,
    "row": 7,
    "col": 7,
    "status": inUse
  },
  {
    "piece": knightPiece,
    "row": 7,
    "col": 1,
    "status": inUse
  },
  {
    "piece": knightPiece,
    "row": 7,
    "col": 6,
    "status": inUse
  },
  {
    "piece": bishopPiece,
    "row": 7,
    "col": 2,
    "status": inUse
  },
  {
    "piece": bishopPiece,
    "row": 7,
    "col": 5,
    "status": inUse
  },
  {
    "piece": queenPiece,
    "row": 7,
    "col": 4,
    "status": inUse
  },
  {
    "piece": kingPiece,
    "row": 7,
    "col": 3,
    "status": inUse
  }
  ]
};
}
